export const tea = [
  {
    id: 1,
    name: "Trà Dưa Đào Sung Túc",
    price: 58,
    salePrice: 40,
    img: "tra-dao-dua-luoi.jpg",
    cate: "tea",
  },
  {
    id: 2,
    name: "Trà Sen Nhãn Sum Vầy",
    price: 58,
    salePrice: 40,
    img: "tra-sen-nhan.jpg",
    cate: "tea",
  },
  {
    id: 3,
    name: "Trà Hạt Sen Đá",
    price: 45,
    salePrice: 32,
    img: "tra-sen-da.jpg",
    cate: "tea",
  },
  {
    id: 4,
    name: "Trà Hạt Sen Nóng",
    price: 51,
    salePrice: 36,
    img: "tra-sen-nong.jpg",
    cate: "tea",
  },
  {
    id: 5,
    name: "Trà Long Nhãn Hạt Chia",
    price: 45,
    salePrice: 32,
    img: "nhan-hat-chia.png",
    cate: "tea",
  },
  {
    id: 6,
    name: "Trà Đào Cam Sả Đá",
    price: 45,
    salePrice: 32,
    img: "tra-cam-sa-da.jpg",
    cate: "tea",
  },
];

export const coffee = [
  {
    id: 1,
    name: "Mocha Nóng",
    price: 59,
    salePrice: 35,
    img: "mocha-nong.jpg",
    cate: "coffee",
  },
  {
    id: 2,
    name: "Latte Táo Lê Quế Đá",
    price: 58,
    salePrice: 40,
    img: "latte-tao-le-que-da.jpg",
    cate: "coffee",
  },
  {
    id: 3,
    name: "Latte Táo Lê Quế Nóng",
    price: 58,
    salePrice: 40,
    img: "latte-tao-le-que-nong.jpg",
    cate: "coffee",
  },
  {
    id: 4,
    name: "Cappuchino Nóng",
    price: 49,
    salePrice: 34,
    img: "cappuccino.jpg",
    cate: "coffee",
  },
  {
    id: 5,
    name: "Espresso Nóng",
    price: 40,
    salePrice: 28,
    img: "espresso-nong.jpg",
    cate: "coffee",
  },
];

export const iceBlended = [
  {
    id: 1,
    name: "Chocolate Đá Xay",
    price: 58,
    salePrice: 40,
    img: "chocolate-ice-blended.jpg",
    cate: "iceBlended",
  },
  {
    id: 2,
    name: "Đào Việt Quất Đá Xay",
    price: 58,
    salePrice: 40,
    img: "dao-viet-quat.jpg",
    cate: "iceBlended",
  },
  {
    id: 3,
    name: "Cookie Đa Xay",
    price: 58,
    salePrice: 40,
    img: "cookies-da-xay.jpg",
    cate: "iceBlended",
  },
  {
    id: 4,
    name: "Sinh Tố Việt Quất",
    price: 58,
    salePrice: 40,
    img: "sinh-to-viet-quoc.jpg",
    cate: "iceBlended",
  },
  {
    id: 5,
    name: "Matcha Đá Xay",
    price: 58,
    salePrice: 40,
    img: "matcha-da-xay.jpg",
    cate: "iceBlended",
  },
];

export const snack = [
  {
    id: 1,
    name: "Bánh Mì Que Pate Cay",
    price: 12,
    salePrice: null,
    img: "banh-mi-que-pate.jpg",
    cate: "snack",
  },
  {
    id: 2,
    name: "Chà Bông Phô Mai",
    price: 32,
    salePrice: null,
    img: "cha-bong-pho-mai.jpg",
    cate: "snack",
  },
  {
    id: 3,
    name: "Croissant Trứng Muối",
    price: 32,
    salePrice: null,
    img: "croissant-trung-muoi.jpg",
    cate: "snack",
  },
  {
    id: 4,
    name: "Bánh Mì VN Thịt Nguội",
    price: 29,
    salePrice: null,
    img: "banh-mi-vn-thit-nguoi.jpg",
    cate: "snack",
  },
];

export const atHome = [
  {
    id: 1,
    name: "Cà phê sữa đá pack 6 lon",
    price: 83,
    salePrice: null,
    img: "pack-ca-phe-sua-da.jpg",
    cate: "atHome",
  },
  {
    id: 2,
    name: "Cà Phê Rich Finish Gu Đậm Tinh Tế 350gr",
    price: 65,
    salePrice: 89,
    img: "ca-phe-rich-finish-dam.jpg",
    cate: "atHome",
  },
  {
    id: 3,
    name: "Cà Phê Peak Flavor Hương Thơm Đỉnh Cao 350gr",
    price: 65,
    salePrice: 89,
    img: "ca-phe-peak-flavor.jpg",
    cate: "atHome",
  },
  {
    id: 4,
    name: "Cà Phê Arabica",
    price: 98,
    salePrice: null,
    img: "ca-phe-arabica.jpg",
    cate: "atHome",
  },
];

export const all = coffee.concat(tea);
